{
 "title": "Basic Panels",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "MonitorAgent's CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitorAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> window(every: 1s)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MonitorAgent's Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitorAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> window(every: 1s)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MonitorAgent's Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitorAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_in\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitorAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_out\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MonitorAgent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  { "title": "StorageAgent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "StorageAgent's CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StorageAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> window(every: 1s)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "StorageAgent's Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StorageAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> window(every: 1s)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "StorageAgent's Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StorageAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_in\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"StorageAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_out\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "DisplayerAgent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DisplayerAgent's CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DisplayerAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> group(columns: [\"cpu\"])\n  |> window(every:1s)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DisplayerAgent's Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DisplayerAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> window(every: 1s)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DisplayerAgent's Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Measurements\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DisplayerAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_in\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DisplayerAgent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"network_out\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}